"""
Persistence for users, access (CTX assignments) and the audit trail.

PostgreSQL only. The schema is created and changed exclusively by Alembic
(`alembic upgrade head`, see migrations/) - this module only describes the
tables so the app can query them, and refuses to start if the database is
not at the latest migration.

One database (uda_1325), separate schemas by purpose:
  DB_SCHEMA       app configuration (users, access, audit ...) AND the AI result
                  tables (contract_summary, account_summary, web_claims_summary,
                  contract_recommendation) - the AWS job writes those directly.
  DB_SCHEMA_DATA  the contract/claims serving data loaded from Snowflake.

IDs are UUIDv7, generated by the database (`DEFAULT uuidv7()`: built in from
PostgreSQL 18; the first migration adds an equivalent function on older
servers), so any writer - this app, the AWS job, a psql session - gets
time-ordered unique IDs without coordinating or generating them itself.
"""
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import DateTime, ForeignKey, MetaData, String, Uuid, create_engine, func, select, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column, relationship, sessionmaker

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is not set. Point it at PostgreSQL, e.g. "
        "postgresql+psycopg://app:change-me@localhost:5433/uda_1325 (see docker-compose.yml and .env.example)."
    )
SCHEMA = os.environ.get("DB_SCHEMA", "ai_recommendations")
DATA_SCHEMA = os.environ.get("DB_SCHEMA_DATA", "app_data")

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
    pool_size=int(os.environ.get("DB_POOL_SIZE", "5")),
    max_overflow=int(os.environ.get("DB_MAX_OVERFLOW", "5")),
    connect_args={"options": "-c timezone=UTC"},
)
SessionLocal = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def iso(dt: datetime | None) -> str | None:
    if dt is None:
        return None
    if dt.tzinfo is None:  # defensive: treat a naive value as UTC
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


class Base(DeclarativeBase):
    metadata = MetaData(schema=SCHEMA)


_UUID7 = text("uuidv7()")
_NOW = func.now()


class Ctx(Base):
    """An area code (3 digits, e.g. "034"). The name is what admins see when
    assigning access - codes are auto-discovered from the loaded contracts
    (see sync_ctx_codes) and named by an admin afterwards."""
    __tablename__ = "ctx"
    code: Mapped[str] = mapped_column(String(3), primary_key=True)
    name: Mapped[str] = mapped_column(String(100))


class User(Base):
    __tablename__ = "users"
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=_UUID7)
    # Stable identity from the identity provider (Entra "oid" claim). Never
    # key users on email: emails change, and Microsoft explicitly warns
    # against using the email claim for authorization.
    oid: Mapped[str] = mapped_column(String(200), unique=True)
    email: Mapped[str] = mapped_column(String(320))
    name: Mapped[str] = mapped_column(String(200), default="")
    role: Mapped[str] = mapped_column(String(10), default="user")        # admin | user
    status: Mapped[str] = mapped_column(String(10), default="pending")   # pending | active | disabled
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=_NOW)
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ctx_links: Mapped[list["UserCtx"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", lazy="selectin"
    )


class UserCtx(Base):
    __tablename__ = "user_ctx"
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey(f"{SCHEMA}.users.id"), primary_key=True)
    ctx_code: Mapped[str] = mapped_column(ForeignKey(f"{SCHEMA}.ctx.code"), primary_key=True)
    user: Mapped[User] = relationship(back_populates="ctx_links")
    ctx: Mapped[Ctx] = relationship(lazy="joined")


class AuditLog(Base):
    """Append-only: nothing in the app updates or deletes rows here."""
    __tablename__ = "audit_log"
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=_UUID7)
    at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=_NOW)
    actor_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, nullable=True)
    actor_email: Mapped[str | None] = mapped_column(String(320), nullable=True)
    action: Mapped[str] = mapped_column(String(50))
    entity: Mapped[str] = mapped_column(String(50))
    entity_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ctx_code: Mapped[str | None] = mapped_column(String(3), nullable=True)
    detail: Mapped[dict | None] = mapped_column(JSONB, nullable=True)


def ensure_migrated() -> None:
    """Refuses to start against a database that isn't at the latest Alembic
    revision, with the command that fixes it - far better than a cryptic
    'relation does not exist' on the first request."""
    from alembic.config import Config
    from alembic.runtime.migration import MigrationContext
    from alembic.script import ScriptDirectory

    cfg = Config(str(Path(__file__).parent / "alembic.ini"))
    head = ScriptDirectory.from_config(cfg).get_current_head()
    with engine.connect() as conn:
        current = MigrationContext.configure(conn, opts={"version_table_schema": SCHEMA}).get_current_revision()
    if current != head:
        raise RuntimeError(
            f"Database is at migration {current!r} but the app needs {head!r}. "
            "Run `alembic upgrade head` from the backend folder."
        )


def get_db():
    with SessionLocal() as db:
        yield db


def audit(db: Session, actor: User | None, action: str, entity: str,
          entity_id=None, ctx_code: str | None = None, detail: dict | None = None) -> None:
    """Adds an audit row to the caller's transaction (no commit here, so the
    audit entry and the change it describes succeed or fail together)."""
    db.add(AuditLog(
        actor_id=actor.id if actor else None,
        actor_email=actor.email if actor else None,
        action=action,
        entity=entity,
        entity_id=str(entity_id) if entity_id is not None else None,
        ctx_code=ctx_code,
        detail=detail,
    ))


def reconcile_status(user: User) -> None:
    """A user is active iff they're an admin or hold at least one CTX;
    otherwise they're pending. 'disabled' is an explicit admin decision and
    is never changed implicitly."""
    if user.status == "disabled":
        return
    user.status = "active" if (user.role == "admin" or user.ctx_links) else "pending"


def sync_ctx_codes(db: Session, codes) -> list[str]:
    """Registers any CTX code seen in the loaded contracts that isn't in the
    ctx table yet (named after its own code until an admin renames it).
    Returns the codes it added."""
    existing = set(db.scalars(select(Ctx.code)))
    added = sorted(set(codes) - existing)
    for code in added:
        db.add(Ctx(code=code, name=code))
    return added
