"""
Database foundation check. Plain asserts, no framework:

    cd backend && python tests/check_schema.py

Needs a PostgreSQL server (see tests/pg.py). Creates throwaway databases,
migrates them with the real Alembic migration and then writes to the AI result
tables the way the AWS job will: plain INSERTs that omit the version columns.
"""
import os
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND))
os.chdir(BACKEND)

import psycopg  # noqa: E402
from psycopg import errors  # noqa: E402
from psycopg.rows import dict_row  # noqa: E402
from sqlalchemy.engine import make_url  # noqa: E402

import pg  # noqa: E402

S = "ai_recommendations"
URL = pg.new_database()
DSN = make_url(URL).set(drivername="postgresql").render_as_string(hide_password=False)
os.environ.update(DATABASE_URL=URL, DATA_SOURCE="synthetic", AUTH_MODE="dev", SESSION_SECRET="x" * 40)


def conn(autocommit=True):
    return psycopg.connect(DSN, autocommit=autocommit, row_factory=dict_row)


def raises(exc, sql, *params):
    with conn() as c:
        try:
            c.execute(sql, params)
        except exc:
            return
        raise AssertionError(f"expected {exc.__name__} from: {sql[:80]}")


# ------------------------------------------------------------------ 1. UUIDv7
with conn() as c:
    ids = [r["u"] for r in c.execute("SELECT uuidv7() AS u FROM generate_series(1, 2000)")]
    assert len(set(ids)) == 2000, "uuidv7() produced duplicates"
    assert all(i.version == 7 for i in ids), "not all UUIDs are version 7"
    assert all(i.variant == uuid.RFC_4122 for i in ids)
    now_ms = time.time() * 1000
    assert all(abs(int(i.hex[:12], 16) - now_ms) < 10_000 for i in ids), "embedded timestamp is not 'now'"
    row = c.execute(f"INSERT INTO {S}.users (oid, email) VALUES ('o1', 'a@x.com') RETURNING id, status, role").fetchone()
    assert row["id"].version == 7 and row["status"] == "pending" and row["role"] == "user"  # server-side default id + defaults
print("ok - ids are UUIDv7 (version, variant, timestamp, uniqueness), generated by the database")

# ------------------------------------------------------------------ 2. version chain, all four tables
TABLES = [  # table, key column, version column, payload column
    ("contract_summary", "contractid", "ai_summary_version", "ai_summary"),
    ("account_summary", "accountid", "ai_summary_version", "ai_summary"),
    ("web_claims_summary", "contractid", "ai_summary_version", "ai_summary"),
    ("contract_recommendation", "contractid", "ai_recommendation_version", "ai_recommendation"),
]


def write(c, table, key, ver, payload, key_val, text, **extra):
    """A writer's INSERT: key, ctx and payload only - no id, prev_id, version or is_latest."""
    cols = {key: key_val, "ctx": "034", payload: text, **extra}
    names = ", ".join(cols)
    marks = ", ".join(["%s"] * len(cols))
    return c.execute(f"INSERT INTO {S}.{table} ({names}) VALUES ({marks}) RETURNING *", list(cols.values())).fetchone()


for table, key, ver, payload in TABLES:
    with conn() as c:
        v1 = write(c, table, key, ver, payload, "K1", "one")
        assert v1[ver] == 1 and v1["is_latest"] and v1["prev_id"] is None and v1["id"].version == 7
        assert v1["system"] == "ecare" and v1["language"] == "en" and v1["created_by"] == "pipeline"
        v2 = write(c, table, key, ver, payload, "K1", "two")
        v3 = write(c, table, key, ver, payload, "K1", "three")
        assert (v2[ver], v3[ver]) == (2, 3)
        assert v2["prev_id"] == v1["id"] and v3["prev_id"] == v2["id"], "version chain not linked"
        rows = c.execute(f"SELECT {ver}, is_latest FROM {S}.{table} WHERE {key} = 'K1' ORDER BY {ver}").fetchall()
        assert [(r[ver], r["is_latest"]) for r in rows] == [(1, False), (2, False), (3, True)], rows

        # other key / language / system are independent chains
        assert write(c, table, key, ver, payload, "K2", "x")[ver] == 1
        assert write(c, table, key, ver, payload, "K1", "fr", language="fr")[ver] == 1
        assert write(c, table, key, ver, payload, "K1", "sf", system="salesforce")[ver] == 1
        latest = c.execute(f"SELECT count(*) AS n FROM {S}.{table} WHERE {key} = 'K1' AND is_latest").fetchone()["n"]
        assert latest == 3, "expected one latest per (system, language)"  # en, fr, salesforce

        # the database itself refuses a second 'latest' or a duplicate version number
        raises(errors.UniqueViolation, f"UPDATE {S}.{table} SET is_latest = true WHERE id = %s", v1["id"])
        raises(errors.UniqueViolation, f"UPDATE {S}.{table} SET {ver} = 3 WHERE id = %s", v2["id"])

        # modified_on moves on UPDATE
        before = c.execute(f"SELECT modified_on FROM {S}.{table} WHERE id = %s", (v3["id"],)).fetchone()["modified_on"]
        time.sleep(0.02)
        c.execute(f"UPDATE {S}.{table} SET user_feedback = %s WHERE id = %s", (psycopg.types.json.Jsonb({"thumb": "up"}), v3["id"]))
        after = c.execute(f"SELECT modified_on, user_feedback FROM {S}.{table} WHERE id = %s", (v3["id"],)).fetchone()
        assert after["modified_on"] > before and after["user_feedback"] == {"thumb": "up"}
print("ok - all four tables: version chain, independent keys/languages/systems, latest uniqueness, modified_on")

# ------------------------------------------------------------------ 3. constraints
base = f"INSERT INTO {S}.contract_summary (contractid, ctx, ai_summary"
raises(errors.CheckViolation, base + ") VALUES ('C', '34', 'x')")                       # ctx must be 3 digits
raises(errors.CheckViolation, base + ") VALUES ('C', 'ABC', 'x')")
raises(errors.NotNullViolation, f"INSERT INTO {S}.contract_summary (contractid, ai_summary) VALUES ('C', 'x')")  # ctx required
raises(errors.NotNullViolation, f"INSERT INTO {S}.contract_summary (ctx, ai_summary) VALUES ('034', 'x')")       # key required
raises(errors.CheckViolation, base + ", system) VALUES ('C', '034', 'x', 'jde')")        # system must be known
rec = f"INSERT INTO {S}.contract_recommendation (contractid, ctx, "
raises(errors.CheckViolation, rec + "confidence) VALUES ('R', '034', 1.5)")
raises(errors.CheckViolation, rec + "action_status) VALUES ('R', '034', 'maybe')")
raises(errors.CheckViolation, rec + "outcome) VALUES ('R', '034', 'Won')")
print("ok - constraints reject a bad ctx, missing ctx or key, unknown system, confidence, action_status and outcome")

# ------------------------------------------------------------------ 4. recommendation specifics + JSONB
with conn() as c:
    j = psycopg.types.json.Jsonb
    r1 = c.execute(
        f"INSERT INTO {S}.contract_recommendation (contractid, ctx, ai_recommendation, retention_action_name, confidence, "
        "ai_configuration, input_data, input_hash, evaluation, draft_content) VALUES ('R9', '034', 'why', 'Service check-in', 0.82, %s, %s, %s, %s, %s) RETURNING *",
        (j({"model": "m1", "temperature": 0}), j({"risk": {"score": 71, "factors": [1, 2, {"a": None}]}}), "abc123",
         j({"composite": 8.1, "pass": True}), j({"email_subject": "Hello"}))).fetchone()
    assert r1["action_status"] == "Action required" and r1["outcome"] is None and float(r1["confidence"]) == 0.82
    assert r1["input_data"]["risk"]["factors"][2] == {"a": None} and r1["draft_content"] == {"email_subject": "Hello"}
    c.execute(f"UPDATE {S}.contract_recommendation SET outcome = 'Engaged', action_status = 'Action done' WHERE id = %s", (r1["id"],))
    r2 = write(c, "contract_recommendation", "contractid", "ai_recommendation_version", "ai_recommendation", "R9", "next milestone")
    old = c.execute(f"SELECT outcome, action_status FROM {S}.contract_recommendation WHERE id = %s", (r1["id"],)).fetchone()
    assert (old["outcome"], old["action_status"]) == ("Engaged", "Action done"), "older version lost its outcome"
    assert r2["outcome"] is None and r2["action_status"] == "Action required", "new version should start fresh"
print("ok - recommendation: JSONB round-trips; each version keeps its own status and outcome")

# ------------------------------------------------------------------ 5. concurrent writers
N = 12
errs, barrier = [], threading.Barrier(N)


def worker(i):
    try:
        with conn(autocommit=False) as c:
            barrier.wait()
            write(c, "contract_summary", "contractid", "ai_summary_version", "ai_summary", "RACE", f"w{i}")
            c.commit()
    except Exception as e:  # noqa: BLE001
        errs.append(repr(e))


threads = [threading.Thread(target=worker, args=(i,)) for i in range(N)]
[t.start() for t in threads]
[t.join() for t in threads]
assert not errs, errs
with conn() as c:
    rows = c.execute(f"SELECT id, prev_id, ai_summary_version AS v, is_latest FROM {S}.contract_summary WHERE contractid = 'RACE' ORDER BY ai_summary_version").fetchall()
    assert [r["v"] for r in rows] == list(range(1, N + 1)), [r["v"] for r in rows]
    assert [r["is_latest"] for r in rows] == [False] * (N - 1) + [True]
    assert all(rows[i]["prev_id"] == rows[i - 1]["id"] for i in range(1, N)), "chain broken under concurrency"
print(f"ok - {N} simultaneous writers for one key: versions 1..{N}, one latest, unbroken chain, no errors")

# ------------------------------------------------------------------ 6. ORM models match the migrated tables
import db  # noqa: E402

with conn() as c:
    for table in db.Base.metadata.sorted_tables:
        cols = {r["column_name"] for r in c.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_schema = %s AND table_name = %s",
            (S, table.name))}
        assert cols == {col.name for col in table.columns}, (table.name, cols ^ {col.name for col in table.columns})
print("ok - ORM models and migrated tables list exactly the same columns")

# ------------------------------------------------------------------ 7. migration guard + configurable schemas
unmigrated = pg.fresh_database()
r = subprocess.run([sys.executable, "-c", "import db; db.ensure_migrated()"], capture_output=True, text=True,
                   env={**os.environ, "DATABASE_URL": unmigrated}, cwd=BACKEND)
assert r.returncode != 0 and "alembic upgrade head" in r.stderr, r.stderr[-400:]
r = subprocess.run([sys.executable, "-c", "import db; db.ensure_migrated(); print('migrated')"], capture_output=True, text=True,
                   env={**os.environ, "DATABASE_URL": URL}, cwd=BACKEND)
assert r.returncode == 0 and "migrated" in r.stdout, r.stderr[-400:]

custom = pg.fresh_database()
os.environ.update(DB_SCHEMA="cfg_app", DB_SCHEMA_DATA="cfg_data")
pg.migrate(custom)
os.environ.pop("DB_SCHEMA"); os.environ.pop("DB_SCHEMA_DATA")
with psycopg.connect(make_url(custom).set(drivername="postgresql").render_as_string(hide_password=False), row_factory=dict_row) as c:
    got = {(r["table_schema"], r["table_name"]) for r in c.execute(
        "SELECT table_schema, table_name FROM information_schema.tables WHERE table_schema IN ('cfg_app','cfg_data','ai_recommendations','app_data')")}
    assert ("cfg_app", "contract_summary") in got and ("cfg_app", "users") in got and ("cfg_app", "alembic_version") in got, got
    assert not any(s == "ai_recommendations" for s, _ in got), "default schema should not be touched"
    assert c.execute("SELECT count(*) AS n FROM information_schema.schemata WHERE schema_name = 'cfg_data'").fetchone()["n"] == 1
print("ok - the app refuses an unmigrated database; DB_SCHEMA / DB_SCHEMA_DATA relocate everything")

# ------------------------------------------------------------------ 8. docs/db_roles.sql actually works
suffix = uuid.uuid4().hex[:6]
roles_sql = (BACKEND / "docs" / "db_roles.sql").read_text().replace("ai_writer", f"ai_writer_{suffix}").replace("app_api", f"app_api_{suffix}")
with conn() as c:
    c.execute(roles_sql)
db_name = make_url(URL).database


def as_role(role):
    d = make_url(DSN).set(username=f"{role}_{suffix}", password="CHANGE-ME").render_as_string(hide_password=False)
    return psycopg.connect(d, autocommit=True, row_factory=dict_row)


def denied(c, sql):
    try:
        c.execute(sql)
    except errors.InsufficientPrivilege:
        return
    raise AssertionError("expected permission denied: " + sql[:90])


try:
    with as_role("ai_writer") as w:
        a = write(w, "contract_summary", "contractid", "ai_summary_version", "ai_summary", "ROLE1", "v1")
        b = write(w, "contract_summary", "contractid", "ai_summary_version", "ai_summary", "ROLE1", "v2")  # trigger flips v1 as the writer
        assert (a["ai_summary_version"], b["ai_summary_version"]) == (1, 2) and b["prev_id"] == a["id"]
        write(w, "contract_recommendation", "contractid", "ai_recommendation_version", "ai_recommendation", "ROLE1", "r1")
        denied(w, f"UPDATE {S}.contract_summary SET ai_summary = 'rewritten history'")   # cannot rewrite
        denied(w, f"UPDATE {S}.contract_summary SET is_latest = false")                  # cannot hide the current version either
        denied(w, f"DELETE FROM {S}.contract_summary")
        denied(w, f"SELECT * FROM {S}.users")
        denied(w, f"SELECT * FROM {S}.audit_log")
        denied(w, f"INSERT INTO {S}.users (oid, email) VALUES ('x', 'x')")
    with as_role("app_api") as a_:
        a_.execute(f"UPDATE {S}.contract_recommendation SET outcome = 'Engaged' WHERE contractid = 'ROLE1' AND is_latest")
        a_.execute(f"INSERT INTO {S}.audit_log (action, entity) VALUES ('t', 't')")
        a_.execute(f"SELECT count(*) FROM {S}.users")
        denied(a_, f"DELETE FROM {S}.audit_log")
        denied(a_, f"UPDATE {S}.audit_log SET action = 'tampered'")
        denied(a_, f"DELETE FROM {S}.contract_summary")
        denied(a_, f"UPDATE {S}.alembic_version SET version_num = 'x'")
finally:
    with conn() as c:
        # roles are cluster-wide, so clean up (the database itself is dropped on exit)
        c.execute(f"REVOKE ALL ON ALL TABLES IN SCHEMA {S} FROM ai_writer_{suffix}, app_api_{suffix}")
        c.execute(f"REVOKE ALL ON SCHEMA {S}, app_data FROM ai_writer_{suffix}, app_api_{suffix}")
        c.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA app_data REVOKE SELECT ON TABLES FROM app_api_{suffix}")
        c.execute(f"DROP ROLE ai_writer_{suffix}"); c.execute(f"DROP ROLE app_api_{suffix}")
print("ok - docs/db_roles.sql: the writer can only INSERT versions (no UPDATE/DELETE, no users/audit); the API's audit log is append-only")

print("ALL SCHEMA CHECKS PASSED")
